"use strict";

const { gatherPreflight } = require("../planner/context-preflight");
const { ContextBudget } = require("./context-budget");

class ContextEngine {
  constructor({ workspacePath, semanticRanker }) {
    this.workspacePath = workspacePath;
    this.semanticRanker = semanticRanker; // Optional abstraction
  }

  /**
   * Deterministic Discovery
   * Reuses context-preflight as a ContextSource.
   */
  async _discoverFacts(intent) {
    const items = [];
    const facts = gatherPreflight(this.workspacePath, intent); // real user intent flows into preflight

    // Convert preflight facts into ContextItem contracts
    if (facts.projectName) {
      items.push({
        key: "project.name",
        value: facts.projectName,
        kind: "FACT",
        confidence: 1,
        relevance: 1,
        sources: [{ type: "package.json", path: "package.json" }]
      });
    }

    if (facts.stack) {
      items.push({
        key: "backend.framework",
        value: facts.stack,
        kind: "FACT",
        confidence: 1,
        relevance: 1,
        sources: [{ type: "package.json", path: "package.json" }]
      });
    }

    if (facts.hasAuth) {
      items.push({
        key: "project.hasAuth",
        value: true,
        kind: "FACT",
        confidence: 1,
        relevance: 1,
        sources: [{ type: "package.json", path: "package.json" }]
      });
    }

    if (facts.contextBrief && typeof facts.contextBrief === "object") {
      items.push({
        key: "context.brief",
        value: facts.contextBrief,
        kind: "FACT",
        confidence: 1,
        relevance: 1,
        sources: [{ type: "context-brief", path: "orquestrador/bin/context-brief.js" }]
      });
    }

    if (facts.devState) {
      for (const [devFile, content] of Object.entries(facts.devState)) {
        items.push({
          key: `devstate.${devFile}`,
          value: content,
          kind: "FACT",
          confidence: 1,
          relevance: 1,
          sources: [{ type: "dev-file", path: devFile }]
        });
      }
    }

    return items;
  }

  /**
   * Main entry point to build TaskRelevantContext.
   *
   * @param {string} intent - User intent.
   * @param {number} maxTokens - Budget allowed.
   */
  async buildContext(intent, maxTokens = 8000) {
    // 1. Deterministic Discovery
    const items = await this._discoverFacts(intent);

    // 2. Local AI Semantic Enrichment
    if (this.semanticRanker) {
      const enrichment = await this.semanticRanker.rankAndEnrich(intent, items);

      // Apply enrichment (without transforming INFERENCE into FACT)
      for (const item of items) {
        if (enrichment[item.key]) {
          const enrich = enrichment[item.key];
          // Update relevance but keep FACT if it was a FACT
          if (enrich.relevance !== undefined) {
            item.relevance = enrich.relevance;
          }
          // Enrichment may suggest confidence updates but deterministic facts stay confidence 1
          if (item.kind !== "FACT" && enrich.confidence !== undefined) {
             item.confidence = enrich.confidence;
          }
        }
      }

      // Add new INFERENCES generated by the AI
      if (enrichment.newInferences) {
         for (const inf of enrichment.newInferences) {
            items.push({
              key: inf.key,
              value: inf.value,
              kind: "INFERENCE", // Never FACT
              confidence: inf.confidence || 0.5,
              relevance: inf.relevance || 1,
              sources: inf.sources || [{ type: "ai-enrichment" }]
            });
         }
      }
    }

    // 3. Context Selection / Budget
    const budgetedItems = ContextBudget.applyBudget(items, maxTokens);

    return {
      intent,
      items: budgetedItems
    };
  }
}

module.exports = { ContextEngine };
